version: "3"
services:
  flow-app:
    stdin_open: true
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: ["npm", "run", "test"]
